version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/conf/mosquitto.conf
      - ./mosquitto/conf/mosquitto.passwd:/mosquitto/conf/mosquitto.passwd
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
    restart: unless-stopped

  mqtt-exporter:
    build: ./mqtt_exporter
    network_mode: host
    devices:
      - /dev/ttyACM0
    depends_on:
      - mosquitto
      - prometheus
    environment:
      - MQTT_ADDRESS="localhost"
    ports:
      - 9000:9000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - prometheus_data:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config/datasources:/etc/grafana/datasources
      - ./grafana/config/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
