{
 "title": "Temperatura Servidor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temperatura Fahrenheit Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "temp_f_server", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatura Fahrenheit Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "temp_f_sensor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatura Celsius Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "temp_c_server", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatura Celsius Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "temp_c_sensor", "legendFormat": "__auto" }
   ]
  }
 ]
}